services:
  mysql:
    image: mysql:8.4
    container_name: web-mentor-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: web_mentor

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
